# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12db900e553cd07bbfa0ff617f56c51187de0aa01aa92e08baa99c19441c44f6049fa67a8c349ff84fdf07eadcd03ee9fd0fbfeca1a927b647d96a44de1c5109

test:
  secret_key_base: e3cc625f82f558622febbbf7ad3f985432f3823fda3b94efc7d15493986fda70375de6c3799889b73d7b6673333a6d2c3482672a6fb3247df62f400f6a852703

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
